site_name: NSKit
repo_url: https://github.com/djpugh/nskit/
edit_uri: blob/main/docs/source/
docs_dir: ./source
site_dir: ./html
nav:
 - index.md
 - usage.md
 - 'Developing':
    - developing/index.md
    - developing/license.md
    - developing/sbom.md
    - 'Test Coverage': coverage.md
 - 'API':
    - 'nskit.common': api/nskit.common.md
    - 'nskit.mixer': api/nskit.mixer.md
    - 'nskit.recipes': api/nskit.recipes.md
    - 'nskit.vcs': api/nskit.vcs.md
 - changelog.md
 - 'Issue Tracker': https://github.com/djpugh/nskit/issues

exclude_docs: |
  mkdocs.yml
theme:
  name: material
  icon:
    logo: material/family-tree
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.prefetch
    - navigation.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - autorefs
  # - def_list
  # - mkdocs-gen-files
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          import:
            - https://jinja.palletsprojects.com/en/3.1.x/objects.inv
          paths: [src]
  # https://github.com/jimporter/mike
  - mike:
      canonical_version: latest
  # https://github.com/pawamoy/mkdocs-coverage
  - coverage:
      page_name: coverage  # default
      html_report_dir: reports/htmlcov
  # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized:
      exclude:
        - coverage.md
      type: iso_date
  - include-markdown
  # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - mkdocs_github_changelog:
      match: '[0-9+].[0-9+].[0-9]+'
  - mkdocs_licenseinfo
# https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages

extra:
  version:
    provider: mike